sudo: required

language: node_js

services:
  - docker

before_script:
  - npm install -g dockerlint
  - docker images
  - cd build/maven && make build;
  - docker images

script: ./scripts/run-docker-lint.sh