version: '2.2'
services:

    consul-server:
        image: jorgeacf/consul-server:1.0.7
        restart: unless-stopped
        network_mode: bridge

    docker-discovery:
        image: jorgeacf/docker-discovery:latest
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        privileged: true
        restart: unless-stopped
        network_mode: bridge
        depends_on:
          - consul-server

#networks:
#    app_net:
#        driver: bridge