version: '2.2'
services:
#    docker-discovery:
#        image: jorgeacf/docker-discovery:latest
#        volumes: 
#          - "/var/run/docker.sock:/var/run/docker.sock"
#        privileged: true
#        network_mode: bridge

    zookeeper:
        image: jorgeacf/zookeeper:3.4.12
        #scale: 3
        network_mode: bridge

    mysql:
        image: jorgeacf/mariadb:10.2.14
        network_mode: bridge

    nifi:
        image: jorgeacf/nifi:1.6.0
        network_mode: bridge

    resource_manager:
        image: jorgeacf/hadoop:2.9.1
        command: "/entrypoint-resource-manager.sh"
        network_mode: bridge

    datanode:
        image: jorgeacf/hadoop:2.9.1
        command: "/entrypoint-node-manager.sh"
        network_mode: bridge

volumes:
  zookeeper_volume:
  mysql_volume:
  nifi_volume:
  yarn_resource_manager_volume:
  yarn_datanode_volume: